version: "3.2"

services:
  faceid:
    image: faceid
    build: ./
    deploy:
      replicas: 1
    environment:
      LISTEN_PORT: 443
    volumes:
      - ./config:/config
      - ./certs:/certs
    networks:
      - outside
#    secrets:
#      - db_pass
#      - db_user

#secrets:
#  db_pass:
#    external: true
#  db_user:
#    external: true

networks:
  outside:
    external:
      name: "host"

